import { useNavigate } from "react-router-dom";
import { FileText, Download, ArrowUpRight } from "lucide-react";
import { Card } from "../components/Card";
import { Loading, ErrorState } from "../components/State";
import { useEngineers } from "../hooks/queries";
import { gradeColor } from "../lib/utils";

export default function Reports() {
  const nav = useNavigate();
  const { data: engineers, isPending, isError } = useEngineers();

  if (isPending) return <Loading label="Loading reports…" />;
  if (isError || !engineers) return <ErrorState message="Couldn't load reports." />;

  const order = ["mithun", "raman", "gauri", "akanksha", "yasir", "abhishek"];
  const list = order.map((id) => engineers.find((e) => e.id === id)).filter(Boolean) as typeof engineers;

  return (
    <>
      <div className="mb-6">
        <h1 className="text-[26px] text-ink font-bold m-0">Reports</h1>
        <p className="text-sm text-mute mt-1">Generated Technical Excellence Reports</p>
      </div>

      <Card className="!p-0 overflow-hidden">
        <div className="px-[22px] py-5 border-b border-border">
          <div className="text-base text-ink font-bold">Latest reports</div>
          <div className="text-[13px] text-mute mt-0.5">Sprint 3 · auto-generated by the AI Report Engine</div>
        </div>

        {list.map((e, i) => (
          <div
            key={e.id}
            className={`grid [grid-template-columns:auto_1fr_auto_auto] gap-4 items-center px-[22px] py-4 ${i < list.length - 1 ? "border-b border-border" : ""}`}
          >
            <div className="w-10 h-10 rounded-[10px] bg-surfaceHi grid place-items-center">
              <FileText size={18} className="text-accent" />
            </div>
            <div>
              <div className="text-[14.5px] text-ink font-semibold">Technical Excellence · {e.name}</div>
              <div className="font-mono text-xs text-faint mt-0.5">
                Score <span style={{ color: gradeColor(e.score) }}>{e.score}/100</span> · 6 categories · Sprint 3
              </div>
            </div>
            <button className="inline-flex items-center gap-1.5 text-[12.5px] text-mute bg-transparent border border-border rounded-lg px-3 py-[7px] cursor-pointer">
              <Download size={13} /> PDF
            </button>
            <button
              onClick={() => nav(`/engineers/${e.id}`)}
              className="inline-flex items-center gap-1.5 text-[12.5px] text-bg bg-accent border-0 rounded-lg px-3.5 py-2 cursor-pointer font-semibold"
            >
              Open <ArrowUpRight size={13} />
            </button>
          </div>
        ))}
      </Card>
    </>
  );
}
